### ISSUE TITLE
Visualizar correctamente el campo de DNI en la orden (Solución)

### ISSUE THREAD

**Issue by grupoeon** [mobbexco/woocommerce#100]
Buen día,

Nos contactó una clienta preguntando por qué no podía ver el campo DNI en los pedidos, pensando que no era obligatorio.

Luego de una breve investigación, determinamos que en realidad si es obligatorio, y el DNI sí se guarda en la base de datos, pero al visualizarlo hay un pequeño error que impide mostrarlo correctamente.

El error se produce en `gateway.php:409`, en la función `display_checkout_fields_data()`:

```
public function display_checkout_fields_data($order)
{
    ?>
    <p>
        <strong>DNI:</strong>
        <?= get_post_meta($order->get_id(), 'billing_dni', true) ?: get_user_meta($order->get_customer_id(), 'billing_dni', true) ?>
    </p>
    <?php
}
```

Al traer un custom field de una orden en WooCommerce, es necesario por convención agregarle un guión bajo al inicio, [esta respuesta lo explica con detalle](https://stackoverflow.com/questions/46824049/woocommerce-order-meta-data-appears-twice-once-with-underscore), y lo menciono porque desconozco si el error está presente en otras partes del plugin.

Esencialmente hay que cambiar esta línea:

```
<?= get_post_meta($order->get_id(), 'billing_dni', true) ?: get_user_meta($order->get_customer_id(), 'billing_dni', true) ?>
```

Por esta:

```
<?= get_post_meta($order->get_id(), '_billing_dni', true) ?: get_user_meta($order->get_customer_id(), 'billing_dni', true) ?>
```

***Nota**: Para la metadata de usuario no hay que poner el guión, sólo para la de orden.*

Nosotros lo arreglamos a mano pero obviamente sin que lo implementen en master cuando se actualice se va a pisar, cualquier cosa nos avisan.

Saludos.

**Comment by jlmobbex** [comment]
Hola @grupoeon, muchas gracias por tus comentarios!

El error se debe a que recientemente cambiamos el nombre del campo en el que se guarda esta información (de `_billing_dni` a `billing_dni`), y no tuvimos en cuenta el nombre anterior al momento de mostrarlo en el panel del pedido.

De todas formas, como este nuevo nombre permitiría que el administrador modifique el valor del campo, volveremos a utilizar el anterior y agregaremos la condición para que lo busque por ambos nombres.

Saludos!

**Comment by erpwoosync** [comment]
¿Podrían ver este error? : https://github.com/mobbexco/woocommerce-subscriptions-v1/issues/4
