### ISSUE TITLE
Campo DNI no visible

### ISSUE THREAD

**Issue by erpwoosync** [mobbexco/woocommerce#104]
Estimados : estamos teniendo este problema en nuestra web, cuando un cliente quiere renovar la suscripción que se venció, le solicita que ponga el DNI pero el campo no esta disponible.

![image](https://user-images.githubusercontent.com/80854721/147755455-042bbc95-26ac-41e0-bb9a-be498eeaf2f5.png)

**Comment by erpwoosync** [comment]
Si necesitan acceso a nuestro sitio, se lo podemos proporcionar!

**Comment by jlmobbex** [comment]
Hola @erpwoosync! Si querés dejarnos el acceso te pido que nos escribas [acá](https://ayuda.mobbex.com/es/kb-tickets/new) (centro de ayuda) para que podamos ayudarte de forma privada. Muchas gracias!

**Comment by erpwoosync** [comment]
> Hola @erpwoosync! Si querés dejarnos el acceso te pido que nos escribas [acá](https://ayuda.mobbex.com/es/kb-tickets/new) (centro de ayuda) para que podamos ayudarte de forma privada. Muchas gracias!

Estimado : ya lo hicimos y nunca tuvimos respuesta...

**Comment by jlmobbex** [comment]
Hola @erpwoosync! Hemos encontrado la causa del error. Existe una interferencia entre los plugins que manejan la vista del checkout en su instalación. Pronto nos vamos a estar comunicando vía mail para verificar alguna configuraciones y brindar una explicación más detallada

**Comment by erpwoosync** [comment]
Estimados : he probado otro plugin de modificación del checkout y tampoco
me funciona en conjunto con sus plugins, se los adjunto.

Me da un error crítico en la sección de configuración del plugin, si
desactivo los plugin de mobbex funciona correctamente.

yith-woocommerce-checkout-manager

Para usar cambiar la extension del archivo de : pdf > zip

*Gabriel Alejandro Diaz*
Asesor Informático / Implementador Sistema / Consultor Infraestructura
E-Mail : ***@***.***
WhatsApp : +543574404388
Tel Oficina Comercial : (011) 5252-7897 Interno 212
Tel Oficina Comercial Directo : 0351-5680455

Jesús is my Lord! / John 14:6

**Comment by asperduti** [comment]
Estoy con el mismo problema.
En mi caso, yo ya solicito el DNI al cliente, y en las configuraciones indique cual es el campo donde esta el DNI.
Pero me marca el mismo error, de que falta completar el DNI-
