### ISSUE TITLE
No respeta custom_dni

### ISSUE THREAD

**Issue by asperduti** [mobbexco/woocommerce#113]
Yo ya solicito el DNI al cliente, y en las configuraciones indique(Utilizar campo de DNI existente ) cual es el campo donde esta el DNI.

Pero el plugin parece que no lo toma en cuenta, desde la última actualización que se realizo. Ya que en el checkout me indica "Complete el campo DNI" y se refiere al Campo DNI que debería agregar el plug-in, pero no lo agrega ya que esta el custom, que previamente solitico.

**Comment by jlmobbex** [comment]
Hola @asperduti! En la opción "Utilizar campo de DNI existente" se debe introducir el valor que tiene el atributo `name` del campo a vincular ¿Nos pasas el valor que estableciste en esa configuración y una URL del sitio para comprobar que esté correcto? Gracias

**Comment by asperduti** [comment]
> Hola @asperduti! En la opción "Utilizar campo de DNI existente" se debe introducir el valor que tiene el atributo `name` del campo a vincular ¿Nos pasas el valor que estableciste en esa configuración y una URL del sitio para comprobar que esté correcto? Gracias

Hola @jlmobbex Gracias!.
Cuando lo instalamos por primera vez, me habían indicado que era el nombre del campo como se guardaba en la db. Y estuvo funcionando. 
Con esto que me comentas, volvió a funcionar.
