### ISSUE TITLE
Problems at checkout

### ISSUE THREAD

**Issue by editorialadhoc** [mobbexco/woocommerce#114]
Once the products have been chosen, when you click on Finish purchase, the system remains without doing anything for several minutes.
The problem is this plugin since deactivating it solves the problem.

**Comment by jlmobbex** [comment]
Hola @editorialadhoc! Para poder ayudarte con el inconveniente, necesito que comentes la siguiente información:
¿Ha establecido las credenciales del plugin en la configuración?
¿Se encuentra activa la opción de pago por redirección?
¿En modo de pruebas sucede el mismo error?
Muchas gracias.

**Comment by jlmobbex** [comment]
Cierro la issue por inactividad en los últimos 30 días.
