### ISSUE TITLE
No carga el logo de GoCuotas en el modal de financiación

### ISSUE THREAD

**Issue by leandroprz** [mobbexco/woocommerce#118]
Al hacer click en el botón de "Ver financiación" cargan los logos de todas las tarjetas menos el de GoCuotas: https://i.ibb.co/hMd729y/gocuotas-error.png

![image](https://i.ibb.co/hMd729y/gocuotas-error.png)

Al intentar abrir la imagen aparece este error:
`AccessDeniedAccess DeniedQQ07WVYBSYEG8W55hWbcUfKD7M7IsOoUFwzdcOuhfjkbJSadjQNepeAj7h3pYG6oFqkQO3JEJJYRbCdFA7p0RHF8uOE=`

Estoy usando:
- WordPress v6.0
- WooCommerce v6.6.1
- Mobbex for Woocommerce v3.8.0

**Comment by jlmobbex** [comment]
Hola @leandroprz, gracias por tu comentario! Ahora mismo el equipo se encuentra trabajando para subir las imagenes faltantes al servidor.

**Comment by leandroprz** [comment]
Hola. Veo que en el último update mencionan una corrección en las rutas de las imagenes, pero este error sigue estando presente.

**Comment by santiag136** [comment]
Estoy recibiendo este error al actualizar: El directorio de instalación es incorrecto (woocommerce-master). Si descargó el zip directamente del repositorio, reinstale el plugin utilizando el archivo wc-mobbex.x.y.z.zip de https://github.com/mobbexco/woocommerce/releases/latest

**Comment by jlmobbex** [comment]
Hola @santiag136! Creo una nueva issue para responder a tu caso.

**Comment by jlmobbex** [comment]
Hola @leandroprz! Te comento que la imagen del medio de pago GoCuotas ya se subió al servicio y está disponible en el selector de medios de pago:
![image](https://user-images.githubusercontent.com/69467418/210800358-5531614d-506b-4743-95e6-b97535676870.png)
