### ISSUE TITLE
Click handler en :submit hace fallar formulario de cupones

### ISSUE THREAD

**Issue by nmercado1986** [mobbexco/woocommerce#120]
La siguiente línea en mobbex.bootstrap.js:10, ataja el evento click del botón de submit del form de cupones.
Creo que el selector es demasiado amplio:

```

    // Intercept form button (Bind to click instead of WC trigger to avoid popup) 
    $('form.checkout').on('click', ':submit', function (event) {
        return executePayment(event);
    });

    // Intercept submit for order review
    $('form#order_review').on('submit',
```

Un selector más específico para el botón de submit, como `[name=woocommerce_checkout_place_order]` o `#place_order` aplicaría solo al botón de finalizar pedido y no interceptaría el formulario de cupones.

**Comment by nmercado1986** [comment]
Debería aclarar que este es un theme específico que tiene el form de cupones como un subform de form-checkout.
Imagino que no se quiso apuntar al botón de este form sino solo al de Finalizar pedido.

**Comment by jlmobbex** [comment]
Hola @nmercado1986! Gracias por tus comentarios, ahora mismo estamos trabajando para que este cambio esté disponible en la próxima versión.

**Comment by jlmobbex** [comment]
Hola @chingologram! Te comento que debido a errores al atajar la apertura del modal en la página de pagos para pedidos pendientes hemos decidido revertir el cambio realizado en la PR #133. Revisamos los selectores que utiliza internamente WooCommerce para atajar este evento son los mismos que los que usábamos nosotros ([código donde se utiliza](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/frontend/checkout.js#L16-L17)), por lo que el problema debe resolverse con el equipo que mantiene el tema visual.

**Comment by chingologram** [comment]
@jlmobbex gracias por trabajar en este issue.
Correcto, los selectores están igual a Woo en el observer, aunque a la hora de detectar el envío del form, el elemento se escucha por un `click` en `:submit` lo cual es demasiado amplio y puede interceptar eventos en otros forms. Veo que Woo no escucha el click del submit sino el evento `submit` del form en sí. Por ejemplo, [como hace aquí](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/frontend/checkout.js#L27).
Entiendo que podríamos ignorar este escenario ya que ubicar un form dentro de otro form [no es HTML5 válido](https://stackoverflow.com/questions/555928/is-it-valid-to-have-a-html-form-inside-another-html-form), pero no creo que tengamos una alternativa fácil en este caso. ¿Quizás escuchar el submit del form es más fácil?

**Comment by jlmobbex** [comment]
Buen día @chingologram! No podemos escuchar directamente el evento `submit` debido a que woocommerce lo registra primero y ejecuta un ajax que no nos permite levantar el modal (únicamente permite redireccionar). Igualmente vamos a estar haciendo pruebas para hacer uso de los handlers que dispara wc, pero sólo en la página del checkout. Cualquier cambio te mantengo al tanto!

**Comment by jlmobbex** [comment]
Hola @chingologram! Te comento que finalmente optamos por usar el evento que dispara woocommerce en la página del checkout, de forma que nuestra acción queda nuevamente enlazada al submit del formulario en vez de al click #144
Una vez más, gracias por tus comentarios!
