### ISSUE TITLE
No me permite cambiar el icono en el Checkout

### ISSUE THREAD

**Issue by Facundodr** [mobbexco/woocommerce#125]
en las opciones del plugin tiene una sección donde poner la url del icono que quiero utilizar pero no lo muestra. Sigue manteniendo la url original.

[Imagen1](https://ibb.co/bLF4ww1)
[Imagen2](https://ibb.co/23vRmZj)

**Comment by jlmobbex** [comment]
Hola @Facundodr! Las opciones que mencionás no forman parte de nuestro módulo. Debe haber algún plugin externo que las está mostrando mediante un hook.

De todas formas, es posible que al activar la opción "Modo unificado" que se encuentra dentro de la pestaña "Opciones avanzadas" estas comiencen a funcionar:
![image](https://user-images.githubusercontent.com/69467418/190672833-c780a60a-7622-4779-9953-d1f63a062d11.png)

Esto es debido a que por defecto el plugin trae por API los medios de pago en conjunto con sus imágenes, pero cuando se activa esta opción, se considera que sólo existe un medio de pago y por ello se puede aplicar el ícono.

Avisame si con este cambio si soluciona el inconveniente!

**Comment by jlmobbex** [comment]
Cierro la incidencia por falta de actividad. Espero que la información proporcionada haya sido útil!
