### ISSUE TITLE
Versión 3.9.0 genera "Internal server error" en wordpress

### ISSUE THREAD

**Issue by eduarma** [mobbexco/woocommerce#139]
Buen día.
Al actualizar de la versión 3.8.1 a la 3.9.0, al tratar de finalizar una venta (ir a la página de pago con mobbex), la página se carga con error, "Internal Server Error" de wordpress. 
Al volver a la versión 3.8.1 funciona perfectamente.
Por favor si pueden verificar y corregir el error. 
Wordpress 6.0.3
Woocommerce 7.0.0
Tema Avada 7.8.1
Gracias. Saludos.

**Comment by jlmobbex** [comment]
Hola @eduarma! Muchas gracias por tus comentarios. Hoy publicamos una nueva versión del plugin que mejora el manejo de algunos errores comunes en el checkout. Te pido que actualices el plugin y repitas las pruebas para comprobar si este persiste con los últimos cambios. Saludos!

**Comment by eduarma** [comment]
Buen día Javier.
Sí, con la 3.9.1 se arregló.
Muchas gracias.
Saludos.
Eduardo
