### ISSUE TITLE
El directorio de instalación es incorrecto (woocommerce-master)

### ISSUE THREAD

**Issue by jlmobbex** [mobbexco/woocommerce#153]
Estoy recibiendo este error al actualizar: El directorio de instalación es incorrecto (woocommerce-master). Si descargó el zip directamente del repositorio, reinstale el plugin utilizando el archivo wc-mobbex.x.y.z.zip de https://github.com/mobbexco/woocommerce/releases/latest

_Originally posted by @santiag136 in https://github.com/mobbexco/woocommerce/issues/118#issuecomment-1352444548_

**Comment by jlmobbex** [comment]
Hola @santiag136! Gracias por tus comentarios, este error ocurre debido a que el plugin fue instalado utilizando el código fuente del plugin (en lugar hacerlo desde el asset de versión). La solución pasa por desinstalar y reinstalar el plugin mediante el archivo wc-mobbex.x.y.z.zip de [la última release](https://github.com/mobbexco/woocommerce/releases/latest). Aclaro también que todas las configuraciones se mantienen al realizar este proceso.

**Comment by santiag136** [comment]
Listo, justo estaba reinstalando, ahí vi que quedó todo igual que antes y sin el error. Abrazo!

**Comment by JODURANT** [comment]
Hola,

Tengo la version de Mobbex :  3.11.0
Tengo el mismo problema que santiag136 : el directorio de instalación es incorrecto (woocommerce-master). Si descargó el zip directamente del repositorio, reinstale el plugin utilizando el archivo wc-mobbex.x.y.z.zip de https://github.com/mobbexco/woocommerce/releases/latest

Borre el plugin, la volvi a cargar con el ultimo archivo zip ([wc-mobbex.3.11.0.zip], pero no cambio el problema, Y no puedo activar el plugin.
No encuentro el archivo wc-mobbex.x.y.z.zip Me podrias ayudar por favor?

Saludos,

Jo
