### ISSUE TITLE
El pago con Mobbex no genera la relativa vetna en woocommerce

### ISSUE THREAD

**Issue by Noemiiiiii** [mobbexco/woocommerce#16]
Hola, las ventas que son pagadas a través de Mobbex, no registran la venta en Woocommerce.
Eso significa que no me llega la ficha con los detalles del comprador (si quiere envío o no y en el caso de que si , su dirección) además, y CRUCIAL ...no descuenta el producto de stock disponible....con lo cual sigue vendiendo algo que por ahí ya no está disponible.

**Comment by mobbexdev** [comment]
Hola, esto se debe a que el sitio no está recibiendo el IPN que envía Mobbex al sitio, esto puede deberse a varios factores relacionados con el hosting, por favor escribinos a soporte@mobbex.com para poder revisar nuestros registros y contarte qué está sucediendo ya que no lo podemos hacer por esta via. Muchas gracias!!!
