### ISSUE TITLE
Error en Administrador de Wordpress

### ISSUE THREAD

**Issue by erpwoosync** [mobbexco/woocommerce#163]
Estimados : vuestro plugin genera un conflicto con nuestro plugin de sincronizacion de productos en wp-admin

Fatal error: Uncaught Error: Call to a member function get_customer() on null in /home/customer/www/ferromar.com.ar/public_html/wp-content/plugins/woocommerce-mobbex/controllers/checkout.php:40 Stack trace: #0 /home/customer/www/ferromar.com.ar/public_html/wp-includes/class-wp-hook.php(310): Mobbex\Controller\Checkout->add_checkout_fields(Array) #1 /home/customer/www/ferromar.com.ar/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array) #2 /home/customer/www/ferromar.com.ar/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(1628): apply_filters('woocommerce_bil...', Array, 'AR') #3 /home/customer/www/ferromar.com.ar/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(253): WC_Countries->get_address_fields('AR', 'billing_') #4 /home/customer/www/ferromar.com.ar/public_html/wp-content/plugins/woocommerce-cianbox-integration/admin/class-cianbox-settings.php(1525): WC_Checkout->get_checkout_fields('billing') #5 /home/customer/www/ferromar.com.ar/public_html/ in /home/customer/www/ferromar.com.ar/public_html/wp-content/plugins/woocommerce-mobbex/controllers/checkout.php on line 40
Ha habido un error crítico en esta web. Por favor, comprueba la bandeja de entrada del correo electrónico del administrador de tu sitio para obtener instrucciones.

en esta ubicacion se produce el conflicto
/wp-admin/options-general.php?page=cianbox-settings

![3440943b-5276-4579-815c-b65da5c7d85a](https://user-images.githubusercontent.com/80854721/217534374-0cc3b7ea-a5b6-4511-a285-455965690b4b.jpeg)

Asi se ve nuestro plugin con el de uds desabilitado o no instalado.

![Captura](https://user-images.githubusercontent.com/80854721/217534890-9b70e14a-6740-4c21-ab59-3501a00b6ce7.JPG)

**Comment by jlmobbex** [comment]
Hola @erpwoosync! Te comento ya está publicada la versión de nuestro plugin que soluciona este inconveniente (https://github.com/mobbexco/woocommerce/releases/tag/3.12.0). Una vez más, gracias por tus comentarios!
