### ISSUE TITLE
Mobbex doesn´t show warning on require fields

### ISSUE THREAD

**Issue by aeghio** [mobbexco/woocommerce#175]
The payment method "mobex" doesn´t show the warning when some required field is empty.
We are using it on wordpress/woocommerce/ with divi theme.
you can take a look buying some promo on https://qa.azulformacionsuperior.com/

**Comment by jlmobbex** [comment]
Hola @aeghio! Gracias por tu comentario, ya no encontramos revisando el error en el sitio. Parece haber algún tipo de incompatibilidad con el tema que están utilizando. Apenas tengamos más novedades te aviso.

**Comment by aeghio** [comment]
Excelente @jlmobbex 
A disposición para lo que necesiten.
El site aún no está productivo por lo que podemos hacer pruebas si quisieran.
Saludos

**Comment by jlmobbex** [comment]
El inconveniente quedó corregido en la versión 3.13.1 del plugin (#180).
