### ISSUE TITLE
Agregar opción para ver el botón de financiación en la página de Checkout

### ISSUE THREAD

**Issue by leandroprz** [mobbexco/woocommerce#183]
Estoy intentando agregar el botón de financiación en la página de Checkout en mi tienda, pero el botón no aparece.

Este es mi código:

```
add_action( 'woocommerce_review_order_after_submit', 'boton_mobbex_financiacion_checkout' );
function boton_mobbex_financiacion_checkout() {
    echo do_shortcode( '[mobbex_button]' );
}
```

Pero veo en el archivo `mobbex-for-woocommerce.php` que el siguiente código sólo permite mostrar el botón en la página de producto o en el Carrito y nada más:

```
    public function shortcode_mobbex_button($params)
    {
        global $post;

        // Try to get shortcode params
        if (isset($params['price'])) {
            $price        = $params['price'];
            $products_ids = isset($params['products_ids']) ? explode(',', $params['products_ids']) : [];
        } else if (is_cart()) {
            $price        = WC()->cart->get_total(null);
            $products_ids = array_column(WC()->cart->get_cart() ?: [], 'product_id');
        } else if ($post && $post->post_type == 'product') {
            $price        = wc_get_product($post->ID)->get_price();
            $products_ids = [$post->ID];
        } else {
            return;
        }
```

Sería posible agregar en futuras actualizaciones la opción para mostrar el botón en la página de Checkout?

Entiendo poco de PHP, pero cambiando el condicional a `} else if ( is_cart() || is_checkout() ) {` mi código sí muestra el botón en la página de Checkout. Pero no quiero modificar archivos del plugin porque en cada actualización voy a tener que volver a hacer el cambio.

**Comment by leandroprz** [comment]
Ahí está. Espero esté bien hecho el PR.
https://github.com/mobbexco/woocommerce/pull/185

**Comment by jlmobbex** [comment]
Cierro esta issue por inactividad en los últimos 30 días (la PR seguirá abierta a espera de los cambios solicitados).
