### ISSUE TITLE
El plugin no ha podido activarse porque ha provocado un error fatal.

### ISSUE THREAD

**Issue by PlasmaDS** [mobbexco/woocommerce#189]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in .../public_html/wp-content/plugins/woocommerce-master/mobbex-for-woocommerce.php on line 12

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in .../public_html/wp-content/plugins/woocommerce-master/mobbex-for-woocommerce.php on line 12

**Comment by PlasmaDS** [comment]
Si, yo hice lo mismo.. Es bueno saber que no era yo solo.
@jlmobbex

**Comment by jlmobbex** [comment]
Hola @mega-publicidad y @PlasmaDS. Gracias por sus comentarios, ya se retiró la actualización para revisar los problemas mencionados.

**Comment by marcelo66** [comment]
Hola. Hay alguna solucion para esto. Ya que varias veces he tratado de instalar. Y sucede lo mismo.
Fatal error: Uncaught Error: Failed opening required 'vendor/autoload.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/mfmedio1/public_html/wp-content/plugins/woocommerce-master/mobbex-for-woocommerce.php:12 Stack trace: #0 /public_html/wp-admin/includes/plugin.php(2314): include_once() #1 /public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape() #2 {main} thrown in /home/mfmedio1/public_html/wp-content/plugins/woocommerce-master/mobbex-for-woocommerce.php on line 12

Saludos

**Comment by jlmobbex** [comment]
@marcelo66, la solución para tu caso pasa por desinstalar el plugin y volverlo a instalar según lo comenté en https://github.com/mobbexco/woocommerce/issues/153.

**Comment by PlasmaDS** [comment]
> @PlasmaDS hice un nuevo análisis sobre el problema que comentás, y es distinto que parece tener @mega-publicidad. En tu caso el problema se da porque la instalación no fue realizada utilizando el comprimido correcto, como se ve en #153.

Si, la habia instalado manual hacia tiempo y no me acordaba como se hacía.
El error se dio primero con actualización automatica, luego intente reinstalar la v3.13.0 manualmente y lo hice mal. Pero enseguida pude instalar la v3.12.0.

Gracias por el aviso.
