### ISSUE TITLE
Versión  3.13.0 error crítico [fatal error]

### ISSUE THREAD

**Issue by mega-publicidad** [mobbexco/woocommerce#191]
Al actualizar automáticamente a la versión 3.13.0 se ha generado un error crítico
![error](https://user-images.githubusercontent.com/28569822/231184284-0d152856-aab6-4e46-ab76-d01bceb53a47.jpg)

Esperamos atentos revisión y ajuste.

Saludos

**Comment by jlmobbex** [comment]
Cierro la issue por ser un duplicado de #189.
