### ISSUE TITLE
Boton de Ver financiacion no funciona

### ISSUE THREAD

**Issue by Sergio0095** [mobbexco/woocommerce#193]
Buenos dias. tengo problemas con el plugin de Mobbex.

no me funciona el boton ver financiacion desde ayer. Ya probe actualizar todos los demas plugin, ultima version de woocomerce.

Tengo la version de Mobbex  Versión 3.12.0 .  
Intente descargar e instalar la ultima version desde el siguiente link.  https://github.com/mobbexco/woocommerce  Pero no me permite activarlo. Lo instalo pero al activarlo me arroja error fatal, que puedo hacer?

LINK AL SITIO. https://sharecomputacion.com/producto/redmi-note-12-pro-5g-256gb-8gb-white/?swcfpc=1

**Comment by jlmobbex** [comment]
Hola @Sergio0095! Gracias por tu comentario. Te arroja error fatal porque no se puede instalar el plugin directamente desde el código fuente, en la issue #153 se explica como instalar correctamente la versión.

En cuanto al problema al mostrar el botón de Ver financiación te voy a pedir que te comuniques directamente con ayuda@mobbex.com, debido a que es posible que se deba a cofiguración del sitio, debido a que esto ya pasó en el pasado en su sitio, como mencionaron en #179 y se solucionó sin cambiar las configs.

**Comment by jlmobbex** [comment]
Te pido que te comuniques por ese medio para poder evaluar los registros y configuración particular, así evitamos publicar cualquier información sensible en Github.
