### ISSUE TITLE
El plugin no ha podido activarse porque ha provocado un error fatal.

### ISSUE THREAD

**Issue by maxisosa** [mobbexco/woocommerce#199]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /plugins/woocommerce-mobbex/mobbex-for-woocommerce.php on line 12 Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /plugins/woocommerce-mobbex/mobbex-for-woocommerce.php on line 12

Versión 3.13.1

**Comment by jlmobbex** [comment]
Hola @maxisosa! Te pido que te comuniques al mail de ayuda@mobbex.com para revisar la configuración de la plataforma, dado que parece tener que ver con que la instalación no está aceptando rutas relativas en los `require` y habría que analizar como cambiar esa configuración.

**Comment by maxisosa** [comment]
Hola @jlmobbex, me comunicare por ese medio. Muchas gracias.
