### ISSUE TITLE
El plugin no ha podido activarse porque ha provocado un error fatal.

### ISSUE THREAD

**Issue by sdobke** [mobbexco/woocommerce#214]
Warning: require_once(/home/sitioweb/public_html/wp-content/plugins/mobbex/vendor/autoload.php): failed to open stream: No such file or directory in /home/sitioweb/public_html/wp-content/plugins/mobbex/mobbex-for-woocommerce.php on line 12

**Comment by GonzaloCortez1976** [comment]
estamos teniendo problemas en la activación si lo instalamos de clientes que ya esta funcionando me provoca inestabilidad en los complementos de woodmart

**Comment by jlmobbex** [comment]
Hola @sdobke y @GonzaloCortez1976! El problema es que se instaló el plugin de forma incorrecta. Desinstalelo y descargue el archivo según se explica en esta issue anterior: https://github.com/mobbexco/woocommerce/issues/153
