### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by dario-camo** [mobbexco/woocommerce#218]
Warning: require_once(/home/c1190196/public_html/escuelaonline/wp-content/plugins/woocommerce-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/c1190196/public_html/escuelaonline/wp-content/plugins/woocommerce-master/mobbex-for-woocommerce.php on line 12

Fatal error: require_once(): Failed opening required '/home/c1190196/public_html/escuelaonline/wp-content/plugins/woocommerce-master/vendor/autoload.php' (include_path='.:/opt/php7-4/lib/php') in /home/c1190196/public_html/escuelaonline/wp-content/plugins/woocommerce-master/mobbex-for-woocommerce.php on line 12

**Comment by jlmobbex** [comment]
Hola @dario-camo! El problema es que se instaló el plugin de forma incorrecta. Desinstalelo y descargue el archivo según se explica en esta issue anterior: https://github.com/mobbexco/woocommerce/issues/153
