### ISSUE TITLE
Error en el modal ver financiacion

### ISSUE THREAD

**Issue by fernandolop** [mobbexco/woocommerce#249]
Hola. En el producto tengo esta configuracion:
<img width="877" alt="Captura de pantalla 2024-01-19 a la(s) 14 32 33" src="https://github.com/mobbexco/woocommerce/assets/23640978/5630acac-5de9-43fa-8570-19c9edd07cd9">
Pero en el modal de ver financiacion lo veo asi:
<img width="654" alt="Captura de pantalla 2024-01-19 a la(s) 14 32 49" src="https://github.com/mobbexco/woocommerce/assets/23640978/21eefe94-789b-4a50-bb5f-e7a3573f30a5">
Se ven los planes que no están habilitados. Intente habilitar y deshabilitar, pero sigue igual.
Gracias por su ayuda

**Comment by jlmobbex** [comment]
Buenas tardes @fernandolop! Recién se publicó una versión que corrige problemas relacionados al guardado de los planes de pago, te pido si podés hacer una prueba con esta última versión y avisarnos si con esto se soluciona

**Comment by fernandolop** [comment]
Solucionado. Gracias
