### ISSUE TITLE
Pay Method

### ISSUE THREAD

**Issue by open24ml** [mobbexco/woocommerce#4]
Tengo 2 medios de pago, en uno aplico un descuento del 10%, al seleccionarlo aparece el descuento pero no lo aplica. Cambio de medio de pago mantiene el cupon y actualiza el precio final. El principal problema es que el cupon se mantiene aunque cambie de medio de pago

I have 2 means of payment, in one I apply a 10% discount, when selected it appears the discount but does not apply. Change of payment method keeps the coupon and updates the final price. The main problem is that the coupon is maintained even if the payment method changes

**Comment by Noemiiiiii** [comment]
I'M HAVING THE SAME ISSUE

**Comment by ConradGalli** [comment]
> I'M HAVING THE SAME ISSUE

Esto es en el checkout de woocommerce? tenes una captura de pantalla del ejemplo?

**Comment by Noemiiiiii** [comment]
YA NO PORQUE LO SOSTITUÍ CON OTRO PLUGIN, PERO SI, ERA EN EL CARRITO DE WC AL FINAL DEL PROCESO DE PAGO
