### ISSUE TITLE
Problema con version 3.1.4 y metodos de pago.

### ISSUE THREAD

**Issue by gLeW10** [mobbexco/woocommerce#45]
Hola al activar mobbex v3.1.4 se desactivan las otras opciones de pago de otros plugins, Como mercadopago.

Lo prove en 2 instalaciones de Woocommerce.

Gracias

**Comment by numanagit** [comment]
+1 Exactamente el mismo problema

**Comment by asperduti** [comment]
Rompe todo el woocomerce.

Hubo que volver para atras...

**Comment by jlmobbex** [comment]
Hola! Gracias por los comentarios, ya deshabilitamos temporalmente la release y estamos revisando el problema para tenerlo solucionado lo antes posible
