### ISSUE TITLE
Woocommerce version check

### ISSUE THREAD

**Issue by promosyofertas** [mobbexco/woocommerce#5]
In line 86 of "mobbex-for-woocommerce.php" the "wc()->version" is not working anymore. Instead of it, WC_VERSION must be used:
//if (version_compare(wc()->version, '2.6', '<'))
if (version_compare(WC_VERSION, '2.6', '<')) {

**Comment by mobbexdev** [comment]
Hola @promosyofertas este cambio se implementó en la versión pusheada hoy del plugin y en las próximas horas estaremos publicando el release. Gracias por tu observación!
