### ISSUE TITLE
Error en Version 3.1.6

### ISSUE THREAD

**Issue by erpwoosync** [mobbexco/woocommerce#52]
He instalado la ultima version y tengo este problema.

supplied for foreach() in /home/customer/www/gabrield9.sg-host.com/public_html/wp-content/plugins/woocommerce-mobbex/includes/helper.php on line 12

Warning: Cannot modify header information - headers already sent by (output started at /home/customer/www/gabrield9.sg-host.com/public_html/wp-content/plugins/woocommerce-mobbex/includes/helper.php:12) in /home/customer/www/gabrield9.sg-host.com/public_html/wp-admin/includes/misc.php on line 1310

Warning: Invalid argument supplied for foreach() in /home/customer/www/gabrield9.sg-host.com/public_html/wp-content/plugins/woocommerce-mobbex/includes/helper.php on line 12

Warning: Cannot modify header information - headers already sent by (output started at /home/customer/www/gabrield9.sg-host.com/public_html/wp-content/plugins/woocommerce-mobbex/includes/helper.php:12) in /home/customer/www/gabrield9.sg-host.com/public_html/wp-includes/pluggable.php on line 1329

**Comment by jlmobbex** [comment]
Hola! Para resolver el problema nos sería de mucha utilidad saber si es la primera vez que instala el módulo o si este error apareció al realizar una actualización. Gracias!

**Comment by jlmobbex** [comment]
Pudimos replicar el problema y será corregido en la próxima versión. Gracias por informar!
