### ISSUE TITLE
Notice: Add permission_callback argument to API REST.

### ISSUE THREAD

**Issue by ConradGalli** [mobbexco/woocommerce#54]
Notice: register_rest_route ha sido llamada de forma incorrecta. A la definición de ruta de la API REST para mobbex/v1/webhook le falta el argumento permission_callback necesario. Para las rutas de la API REST que están pensadas para a ser públicas, usa __return_true como la llamada de permiso. Por favor, visita Depuración en WordPress para más información. (Este mensaje fue añadido en la versión 5.5.0). in /home/matucar/public_html/wp-includes/functions.php on line 5313

**Comment by jlmobbex** [comment]
Gracias por informar del fallo, estamos trabajando para tenerlo corregido en la próxima versión
