### ISSUE TITLE
Duplicated "MobbexGateway" class name.

### ISSUE THREAD

**Issue by ConradGalli** [mobbexco/woocommerce#55]
2021-04-19T16:36:29+00:00 CRITICAL Cannot declare class MobbexGateway, because the name is already in use en /home/matucar/public_html/wp-content/plugins/woocommerce-mobbex/mobbex-for-woocommerce.php en la línea 14

**Comment by ConradGalli** [comment]
> Hola! En este plugin se declara **una única vez** la clase "MobbexGateway", y este nombre de clase tampoco se repite en el resto de plugins que mantenemos oficialmente para WooCommerce.
> 
> En esta situación es posible que un plugin de terceros haya decidido utilizar el mismo nombre que **el plugin oficial de Mobbex** y que éste se encuentre instalado al mismo tiempo, o que se haya instalado el plugin anteriormente en una ubicación incorrecta, duplicando el código al volver a instalarlo.

Están utilizando el plugin oficial de mobbex 3.1.6 únicamente.

**Comment by jlmobbex** [comment]
Bien, entonces es posible que en algún momento se haya descargado e instalado la release incorrectamente, por ejemplo, utilizando el ZIP del código fuente generado por github en lugar del paquete [wc-mobbex](https://github.com/mobbexco/woocommerce/releases/download/3.1.6/wc-mobbex.3.1.6.zip).

Si es este el caso debería verse en la carpeta de plugins un plugin con el nombre del repositorio sumado a la versión descargada (por ejemplo, woocommerce-3.1.6).

**Comment by jlmobbex** [comment]
@ConradGalli No pudimos reproducir el problema de nuestro lado. En caso de que siga sin funcionar recomiendo actualizar el plugin y la plataforma a sus últimas versiones.
