### ISSUE TITLE
Errores en downgrade / migración de v3.3 a v3.2

### ISSUE THREAD

**Issue by ianlucasdiaz95** [mobbexco/woocommerce#70]
Hay algunos errores por un cambio que realizaron en la arquitectura de los datos y como se guardan en la base de datos.
Los atributos de "common_plans" y "advanced_plans" cambiaron y esto presenta errores en el front y back, a su vez requiere que se re-actualizcen los valores de todos los productos para que funcionen ok en la v3.3.

Se puede realizar un FIX que permite trabajar con los dos tipos de datos a la vez:
En archivo "mobbex-for-woocommerce.php" lineas 369 y 400 reemplazar el unserialize con un IF que checkee si es un array:

`        
if(!is_array(get_post_meta(get_the_ID(), 'common_plans', true))){
            $checked_common_plans = unserialize(get_post_meta(get_the_ID(), 'common_plans', true));
        }else{
            $checked_common_plans = get_post_meta(get_the_ID(), 'common_plans', true);
        }
`  
`  
        if(!is_array(get_post_meta(get_the_ID(), 'advanced_plans', true))){
            $checked_advanced_plans = unserialize(get_post_meta(get_the_ID(), 'advanced_plans', true));
        }else{
            $checked_advanced_plans = get_post_meta(get_the_ID(), 'advanced_plans', true);
        }
`

**Comment by jlmobbex** [comment]
Hola @ianlucasdiaz95! Ya deshabilitamos temporalmente la release y tenemos lista la corrección de este error. Gracias por tus comentarios y disculpas por los inconvenientes!
