### ISSUE TITLE
problema con actualización 3.3.1 wordpress

### ISSUE THREAD

**Issue by arielbentivoglio** [mobbexco/woocommerce#74]
al actualizar a la versión 3.3.1 en wordpress me ingresaa texto en los productos dentro del woocommerce 
![error mobbex woocommerce](https://user-images.githubusercontent.com/86375214/123144714-5dacef80-d432-11eb-921a-2513ce152cfc.PNG)

**Comment by arielbentivoglio** [comment]
![error mobbex woocommerce 2](https://user-images.githubusercontent.com/86375214/123145512-48849080-d433-11eb-9338-9cc542f0402f.PNG)

**Comment by jlmobbex** [comment]
Hola @arielbentivoglio. La corrección de este error ya se implementó y quedará publicada en la próxima versión del plugin (3.3.2) que saldrá en esta semana. Gracias por tus comentarios!
