### ISSUE TITLE
Confirmaciones de Pagos

### ISSUE THREAD

**Issue by erpwoosync** [mobbexco/woocommerce#75]
Estimados : estamos teniendo algunos problemas con pedidos en Woocomerce, que se nos pasan al estado cancelado debido a que no recibimos las confirmación que avisa cuando el cliente pago correctamente. 
Sucede en pedidos aleatorios.

Creímos que podía ser cloudflare que nos estuviera bloqueando las notificaciones y permitimos las siguientes rutas para que no sean bloqueadas, ¿es posible que nos falte alguna ruta URI en las permitidas?

![image](https://user-images.githubusercontent.com/80854721/123839534-9c83ef00-d8e3-11eb-8c49-6fd7690ebd25.png)

**Comment by jlmobbex** [comment]
Hola @erpwoosync! Para que el plugin funcione correctamente el sitio debe estar configurado con un certificado de SSL. Si el sitio ya cuenta con este certificado y **todas** las páginas se cargan en https, pruebe activar/desactivar la opción "WebHook por API nueva" en la configuración del plugin.

**Comment by erpwoosync** [comment]
Lo tengo asi.

[image: image.png]

*Gabriel Alejandro Diaz*
Asesor Informático / Implementador Sistema / Consultor Infraestructura
E-Mail : ***@***.***
WhatsApp : +543574404388
Tel Oficina Comercial : (011) 5252-7897 Interno 212
Tel Oficina Comercial Directo : 0351-5680455

Jesús is my Lord! / John 14:6

**Comment by erpwoosync** [comment]
![image](https://user-images.githubusercontent.com/80854721/124331626-f72c7d80-db65-11eb-9100-240a0689f121.png)

**Comment by jlmobbex** [comment]
Hola @erpwoosync! Como este tipo de error suele estar relacionado con la configuración del hosting, te pido que nos escribas a soporte@mobbex.com para poder revisar nuestros registros y ver qué está sucediendo en este caso. Muchas gracias!
