### ISSUE TITLE
Versión 3.3.2 Modal de financiación

### ISSUE THREAD

**Issue by casaagbe** [mobbexco/woocommerce#78]
No funciona correctamente, dado que Es necesario que el CUIT esté configurado y no esta el campo para ingresar el cuit en la configuracion

**Comment by jlmobbex** [comment]
Hola @casaagbe! A partir de la versión 3.3.2 no es necesario introducir el CUIT para que funcione el modal de financiación. Podrías detallarnos que es lo que no está funcionando? Gracias

**Comment by casaagbe** [comment]
Al hacer click en ver financiación no despliega ni muestra nada
En la configuración sigue apareciendo que es necesario introducir cuit.
Pero no está el campo para completar



CASA AGBE - Todo en Aberturas
Puerto de Palos 204 - Villa Domínico - Bs. As.
Tel.: (011) 5365-7062 Líneas rotativas
WhatsApp: 15-34144509
Telegram: t.me/casaagbe
Messenger: m.me/CASAAGBE

www.casaagbe.com.ar

facebook.com/CASAAGBE

Enviado desde Android

**Comment by jlmobbex** [comment]
Gracias por la información! Es posible que los archivos de la versión anterior hayan quedado guardados en la memoria caché. Si tiene algún plugin de este tipo, trate de borrarla y regenere los archivos minificados.

**Comment by casaagbe** [comment]
Purgue la caché de todas las páginas y también purgue nuevamente la caché
minimizada... El problema sigue.

Puede verse en el sitio web... casaagbe.com.ar



CASA AGBE - Todo en Aberturas
Puerto de Palos 204 - Villa Domínico - Bs. As.
Tel.: (011) 5365-7062 Líneas rotativas
WhatsApp: 15-34144509
Telegram: t.me/casaagbe
Messenger: m.me/CASAAGBE

www.casaagbe.com.ar

facebook.com/CASAAGBE

Enviado desde Android

**Comment by casaagbe** [comment]
Vaciada nuevamente la caché de páginas y la caché minimizada sigue el
inconveniente, adjunto capturas de pantalla

CASA AGBE - Todo en Aberturas
Puerto de Palos 204 - V. Dominico - Pcia. Bs. As.
Tel.: (011) 5365-7062 Líneas rotativas
Telegram: casaagbe <http://t.me/casaagbe>
WhatsApp: 15-34144509 <https://wa.me/541134144509>
Messenger: m.me/CASAAGBE <http://m.me/casaagbe>

www.casaagbe.com.ar
Seguinos: Facebook <https://www.facebook.com/CASAAGBE>   Instagram
<https://www.instagram.com/casaagbe>   Telegram
<https://t.me/CasaAgbe_Aberturas>   Twitter <https://twitter.com/CasaAgbe>
 YouTube <https://www.youtube.com/channel/UC25UfO0VgsQVeRHwiSTApNg>






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jlmobbex** [comment]
Hola @casaagbe, gracias nuevamente por la información! Encontramos que el problema se debe a una incompatibilidad con la versión de jQuery que se está ejecutando en su sitio. Pruebe sustituirla utilizando un plugin (por ejemplo jQuery Updater) o insertando el siguiente código en el archivo functions.php:
```
add_action('wp_enqueue_scripts', function () {
  wp_deregister_script('jquery');
  wp_register_script('jquery', 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js', false, null);
  wp_enqueue_script('jquery');
});
```
**Recuerde que la versión debe ser mayor a 1.9.1 y menor que 3.0.0.**

**Comment by casaagbe** [comment]
Hola, no tengo grandes conocimientos en el tema, desde el hosting no me dan
soporte para estos temas. Me podrina guiar al respecto?

"versión de jQuery" es un plugin que tengo instalado?
"*Recuerde que la versión debe ser mayor a 1.9.1 y menor que 3.0.0.*"
respecto a que plugin es esto?
"jQuery Updater" Si instalo esto se soluciona?




CASA AGBE - Todo en Aberturas
Puerto de Palos 204 - V. Dominico - Pcia. Bs. As.
Tel.: (011) 5365-7062 Líneas rotativas
Telegram: casaagbe <http://t.me/casaagbe>
WhatsApp: 15-34144509 <https://wa.me/541134144509>
Messenger: m.me/CASAAGBE <http://m.me/casaagbe>

www.casaagbe.com.ar
Seguinos: Facebook <https://www.facebook.com/CASAAGBE>   Instagram
<https://www.instagram.com/casaagbe>   Telegram
<https://t.me/CasaAgbe_Aberturas>   Twitter <https://twitter.com/CasaAgbe>
 YouTube <https://www.youtube.com/channel/UC25UfO0VgsQVeRHwiSTApNg>






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jlmobbex** [comment]
Como el caso específico está relacionado con la configuración de la tienda, te pido que nos escribas a soporte@mobbex.com para guiarte de forma mucho más detallada acerca de como solucionarlo. Muchas gracias!

**Comment by casaagbe** [comment]
Hola, escribí a soporte mobbex, no tuve respuesta... De todos modos ya lo
solucione descargando plugin para agregar código que me diste.
Lo que estaría bueno es poder ver la financiación no solamente en la
página del producto, sino también en la página de carrito de compras y de
finalizar compra, donde el cliente puede ver los totales y las formas de
financiación de toda la compra.

Saludos

CASA AGBE - Todo en Aberturas
Puerto de Palos 204 - V. Dominico - Pcia. Bs. As.
Tel.: (011) 5365-7062 Líneas rotativas
Telegram: casaagbe <http://t.me/casaagbe>
WhatsApp: 15-34144509 <https://wa.me/541134144509>
Messenger: m.me/CASAAGBE <http://m.me/casaagbe>

www.casaagbe.com.ar
Seguinos: Facebook <https://www.facebook.com/CASAAGBE>   Instagram
<https://www.instagram.com/casaagbe>   Telegram
<https://t.me/CasaAgbe_Aberturas>   Twitter <https://twitter.com/CasaAgbe>
 YouTube <https://www.youtube.com/channel/UC25UfO0VgsQVeRHwiSTApNg>






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
