### ISSUE TITLE
Añadir Field DNI da como resultado un error critico

### ISSUE THREAD

**Issue by franxifra** [mobbexco/woocommerce#8]
Hola, intente añadir DNI con la opción del plugin. Luego intente desactivar la opción y me tira un error crítico cuando quiero ingresar a los ajustes de cualquier método de pago en WooCommerce.  El error crítico desaparece cuando desactivo el plugin. Extrañamente el campo DNI sigue presente aunque elimine o desactive el plugin de Mobbex. Una vez lo vuelvo a instalar de nuevo desde el repositorio me sigue dando el mismo error.

![Screen Shot 2020-08-20 at 15 59 57](https://user-images.githubusercontent.com/20569207/90813776-6dcddd00-e2fe-11ea-93c8-2b50a764e4a9.png)

**Comment by ConradGalli** [comment]
Gracias, lo vamos a revisar!

**Comment by Soopthunder** [comment]
Hola como están, tuve un problema similar, el campo DNI del plugin mobbex lo desactivamos por que no funcionaba y daba un error en el checkout de woocommerce. Pero el problema nuevo viene ahora sumado con lo anterior, lo que sucedió posteriormente es que el por más que se desactive el campo, sigue figurando activado. Tratamos de utilizar plugins para depurar wordpress en general, pero todavía no podemos debido a que el problema persiste desde el plugin de mobbex. Por ultimo tratamos de crear un campo nuevo y enlazarlo desde el plugin de mobbex "utilizar campo de dni existente", pero obtuvimos los mismos resultados y no funciona. Les dejo captura mostrando lo que me dice un plugin de manejo de campos.
![image](https://user-images.githubusercontent.com/44410691/152563479-007d67fa-5735-4bcc-9fc2-bd9f2aa12658.png)
![image](https://user-images.githubusercontent.com/44410691/152563505-0f4d054b-4276-4c21-9696-9707b2adf971.png)
![image](https://user-images.githubusercontent.com/44410691/152563527-c2cbc1a8-87b1-4e23-b84e-0d9dbe2e4570.png)
